name: python 3.6
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - sympy
  - slycot
  - pip
  - pip:
    - BondGraphTools==0.3.7
    - svgpathtools
    - lxml
    - datetime
    - pandas
    - xlrd
    - networkx
    - control
    - cobra

